### ISSUE TITLE
Infomail

### ISSUE THREAD

**Issue by mikaelangman** [d-sektionen/dummy#1]
Infomailssidan är tom.

**Comment by sorsater** [comment]
Funkar om man inte är inloggad?
Wut

**Comment by mikaelangman** [comment]
Formuläret syns nu, men man får ingen respons när man klickar, varken när man subscribar eller av-subscribar

**Comment by JubbeArt** [comment]
Det verkar funka om man clearar chachen.....

**Comment by sorsater** [comment]
Nya användare är separat, tror det bara finns i functions som triggas när någon loggar in för första gången, försökte avsubscriba men fungerade inte.

**Comment by JubbeArt** [comment]
Bra.. eller jag menar det borde funka att avsubscriba. Pröva du cleara chachen och sen gå in på sidan igen? Det är exakt samma kod som förut så nya användare BORDE funka, men kan inte vara 100% säker heller.

**Comment by sorsater** [comment]
Man bör kanske överväga att gå över till något plugin för maillistan istället. Vet inte hur lätt det är att fixa den egenhackade varianten. 

Maillistan finns i adminläget (admin.google.com) och jag försvann inte. Testade att cleara cashen

**Comment by JubbeArt** [comment]
WOOOOOOHOOOOO MAILCHIMP
