### ISSUE TITLE
Stort vitt utrymme mellan innehåll och menyer med JS avslaget

### ISSUE THREAD

**Issue by Rovanion** [d-sektionen/dummy#4]
Kan anses vara ett icke-problem: http://imgur.com/PIVgxvl

**Comment by JubbeArt** [comment]
Konstigt att pilarna i menyn inte visas korrekt. Det är ju ändå bara en font

**Comment by JubbeArt** [comment]
tar nu bort utrymmet om js är avaktiverat, ursäkta att det tog sån tid. Pilarna i menyn är en font och därför blockas de av noscript security suite. Vet inte riktigt vad vi kan göra mot de

**Comment by Rovanion** [comment]
Bra jobbat att det blir gjort i alla fall :D

2016-09-21 17:37 GMT+02:00 Jesper Wrang <notifications@github.com>:
