### ISSUE TITLE
Felaktig CSS på menyföremål med barn

### ISSUE THREAD

**Issue by SebastianCallh** [d-sektionen/dummy#5]
Istället för "hand"-pekaren som visas för menyföremål utan barn (t.ex. Alumni) uppför sig markören som om knappen vore vanlig text. Testat i Firefox 46.0.1.

**Comment by osund** [comment]
För mig är det inte textmarkör utan handpekaren för Alumni i menyn i Firefox 46.0.1 under Linux. Vilket operativsystem använder du?

**Comment by SebastianCallh** [comment]
Yes. Det är menyföremål MED barn som den uppför sig konstigt på. Bekräftat på WIndows 7 och 10, båda i firefox 56.0.1

**Comment by osund** [comment]
Jo, misstolkade det du skrev.

**Comment by JubbeArt** [comment]
Men det borde väl vara så eftersom de länkar med barn inte är länkar i sig själv. Fast de kanske ser bättre ut om muspekaren bara är som vanligt då (alltså en pil)

**Comment by SebastianCallh** [comment]
Jag trodde det var avsikten att de också skulle ha handmarkören. Det ser lite oklart ut att man inte får den när de andra gör det i min mening.

**Comment by JubbeArt** [comment]
Handmarkören brukar bara användas för saker som är klickbara. Har ändrat så att man nu får en vanligt pil istället för 'text-väljar-pekaren'
