### ISSUE TITLE
Omdirigeringsfel med liu-id + giltig epost

### ISSUE THREAD

**Issue by Fluffet** [d-sektionen/dummy#6]
Man ska ju logga in med sitt liu-id, t.ex `freoh365`.

Om man dock försöker logga in med rätt lösenord till sitt giltiga liu-id + mail i användarnamnsfältet, t.ex `freoh365@student.liu.se` blir man omdirigerad till "Error creating user", istället för en normal errorsida som man kommer till om man t.ex använt en ej existerande mail eller fel lösenord.

Jag loggar inte in så ofta så det var lite förvirrande, trodde jag angivit fel lösenord typ 4 gånger innan jag tog bort mailbiten från användarmailet. Behövs ett lite tydligare felmeddelande kanske, eller faktiskt skriva "LiU-id" i inloggningsformuläret. Peace!

**Comment by osund** [comment]
Det "står" redan LiU-ID som placeholder (`<input type="text" name="log" placeholder="LiU-ID">`), men felhanteringen borde förbättras som sagt.

**Comment by JubbeArt** [comment]
Man kan nu logga in med sin mail också
