### ISSUE TITLE
Startsidan

### ISSUE THREAD

**Issue by rq-abrahamsson** [d-sektionen/dummy#8]
Det här är mycket en smakfråga skulle jag säga. Men jumbotronen på startsidan är bilder roteras tycker jag borde försvinna när man scrollar ner på samma sätt som sektionsloggan gör. Det känns hur som helst som att den tar mer plats än den behöver enligt mig.

**Comment by JubbeArt** [comment]
Lekte runt lite med idén och fick till de här: https://beta.d-sektionen.se/ 
Tycker själv det ser väldigt konstigt ut, vad tycker du?

**Comment by myggan25** [comment]
Håller helt klart med om att det ser lite konstigt ut och det är bättre som det är på orginalsidan just nu. Det jag ville var att informationen på startsidan skulle framhävas mer. Det var när jag satt på min 15" skärm som jag saknade det, nu när jag sitter på min 24" skärm ser jag mycket av sidan ändå. Så det kanske är bäst som det är nu ändå!

**Comment by JubbeArt** [comment]
Jo, det blir ju problem med mindre skärmar, då slidern + headern tar upp över 70% av skärmen.
Jag gillar ändå att ha en relativt stor D-sektionen-logga och har redan gjort slidern så liten som jag tycker är okej. Men jag har ändå 1920x1080 upplösning på min laptop så de kanske är därför. Någon annan idé för att få informationen att synas bättre?

**Comment by myggan25** [comment]
Nja faktiskt inte, det kanske är tillräckligt bra nu ändå? Kan ju vara om man tar bort den helt men det är nog inget alternariv? ;)

**Comment by JubbeArt** [comment]
Njaaaaaaaaaa helst inte :) Vi skulle ju kunna ta den här approachen antar jag: http://motherfuckingwebsite.com/

**Comment by myggan25** [comment]
Haha det där såg ju riktigt bra ut (y) ;) haha

**Comment by osund** [comment]
Själv tycker jag det är lite för luftigt med 2560x1080: https://i.imgur.com/z9WkYDP.png
